# Generated by Django 3.1.7 on 2021-03-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptedUser',
        ),
    ]
